warning_threshold: 15

line_length:
    warning: 120
    error: 150
    
function_body_length:
    warning: 80
    error: 150

identifier_name:
  allowed_symbols: "_"
  min_length: 2
  max_length:
    warning: 90
    error: 1000
  excluded:
    - id

opt_in_rules:
    - empty_count
    - force_unwrapping
    - private_outlet

excluded:
    - Pods
    - ShopTests

disabled_rules:
    - trailing_whitespace
    - cyclomatic_complexity
    - redundant_optional_initialization
    - function_parameter_count
